# Generated by Django 4.2.21 on 2025-11-20 00:54

from django.db import migrations
import user_control.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0002_branch_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_control.models.UserManager()),
            ],
        ),
    ]
