# Generated by Django 4.2.20 on 2025-05-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0002_user_branch_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_adjust',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
