# Generated by Django 5.2 on 2025-04-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Bussines',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='documento_nro',
            new_name='document_number',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='producto_nombre',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='cantidad',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='precio',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rol',
        ),
        migrations.AddField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('output', 'Output')], default='compra', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
