# Generated by Django 5.2 on 2025-04-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_business_delete_bussines_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
