# Generated by Django 4.2.20 on 2025-05-08 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='control.business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
