# Generated by Django 5.2.1 on 2025-08-19 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='control.supplier'),
        ),
    ]
