# Generated by Django 4.2.20 on 2025-05-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_product_business_alter_business_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
        migrations.AlterField(
            model_name='business',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
