# Generated by Django 5.2.1 on 2025-09-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_movement_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
