# Generated by Django 4.2.20 on 2025-04-29 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_remove_movement_product_name_movement_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='control.business'),
            preserve_default=False,
        ),
    ]
