# Generated by Django 4.2.20 on 2025-04-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_product_business'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
