# Generated by Django 4.2.20 on 2025-05-09 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_remove_movement_document_number_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='branch_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='control.branch'),
        ),
        migrations.AddField(
            model_name='stock',
            name='minimum_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movement',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_to', to='control.branch'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer')], max_length=20),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='control.business')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='control.category'),
        ),
    ]
