# Generated by Django 5.2.1 on 2025-09-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('business', 'name')},
        ),
    ]
