# Generated by Django 4.2.20 on 2025-05-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_movement_branch_from_stock_minimum_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('adjustment_note', 'Adjustment Note'), ('transfer_note', 'Transfer Note')], max_length=20),
        ),
    ]
