# Generated by Django 4.2.20 on 2025-05-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
