# Generated by hand to enforce case-insensitive uniqueness and optional price.

from django.db import migrations, models
import django.db.models.functions as functions


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_document_unique_and_movement_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(functions.Lower('name'), 'business', name='uniq_branch_business_name_ci'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(functions.Lower('name'), name='idx_branch_lower_name'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(functions.Lower('name'), 'business', name='uniq_category_business_name_ci'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(functions.Lower('name'), name='idx_category_lower_name'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(functions.Lower('name'), 'business', name='uniq_product_business_name_ci'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(functions.Lower('name'), name='idx_product_lower_name'),
        ),
    ]
