# Generated by Django 4.2.21 on 2025-11-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_remove_supplier_model'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movement',
            name='movement_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='movement',
            name='movement_type_idx',
        ),
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer')], db_index=True, max_length=20),
        ),
    ]
